If a decorator is added to a function / method, then we could get errors like:
```
ValueError: fn() requires a code object with 0 free vars, not 1
```

This fixes this problem.

PiperOrigin-RevId: 719862194